### PR TITLE
Delete all notes Changed

### PR DESCRIPTION
**Pull request by uhalder**
This is another implementation by not using any spacer and making the Full Screen Message center aligned.
The problem earlier was with .verticalScroll(rememberScrollState()). This was not allowing the column to use full screen so I had to add spacer.
In this implementation I have slightly changed the layout. I have kept the InterviewDetailForNote fixed and kept the notes inside the scroll area. 
Let me know if this is fine with you or would you like me to find another solution to make the whole screen scrollable?

screenshot_1
screenshot_2

### CODE REVIEW

**Review by Audienix — APPROVED** [review]
I like the detailed reasoning of the original issue. Thanks for clarifying and making the fix. You have done the right fix and UI behavior of sticky interview header is also expected behavior. You can merge it.

**Comment by Audienix** [comment]
I am assuming you will cover this UI change of delete note in another PR.
image

**Comment by Audienix** [comment]
@uhalder  Oh just now noticed this UI bug. `Edit your interview Notes` header should be left aligned. It has become center aligned now because of the horizontal alignment of the Column.
image

**Comment by uhalder** [comment]
> @uhalder Oh just now noticed this UI bug. `Edit your interview Notes` header should be left aligned. It has become center aligned now because of the horizontal alignment of the Column. image

Fixed the issue

**Pull request merged**
